#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" nexus
usermod -o -u "$PUID" nexus

cat /etc/s6-overlay/s6-rc.d/init-adduser/branding

if [[ -f /donate.txt ]]; then
    echo '
To support the app dev(s) visit:'
    cat /donate.txt
fi
echo '
To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────'
echo "
User UID:    $(id -u nexus)
User GID:    $(id -g nexus)
───────────────────────────────────────
"

lsiown nexus:nexus /app
lsiown nexus:nexus /config
lsiown nexus:nexus /defaults
